### ISSUE TITLE
Keyboard controls issue (`Home`, `Shift` + `Tab`) 

### ISSUE THREAD

**Issue by Konrud** [scottaohara/accessible_accordions#12]
`Home` and `Shift` + `Tab` keys do not work. Tested on [Accessible accordions demo page](https://github.com/scottaohara/a11y_accordions) on Windows 7, Chrome 77.

**Comment by scottaohara** [comment]
Hi @Konrud 
I do not have a windows 7 machine to test further, so i'm wondering if you could provide more information?

For instance, I have no key events listening for shift + tab, so I'm curious as to why standard keyboard functionality isn't working for you.

What behavior are you experiencing with the Home key, standard back to the top of the document behavior?  Other?

**Comment by Konrud** [comment]
In your Keyboard Controls section, `Home` and `Shift` + `Tab` keys are mentioned to be navigation keys. As far as I know, that won't work by default, at least on Windows machine. As to `Home` button it does nothing.

**Comment by scottaohara** [comment]
>Shift + Tab keys are mentioned to be navigation keys. As far as I know, that won't work by default, at least on Windows machine

Why wouldn't Shift + tab work by default?  I still don't understand what the issue is here.  This is just noting standard keyboard navigation, nothing more.

As far as the home button, it shouldn't do anything unless an accordion button is focused (and not the first in an accordion as it would just navigate to itself then).

**Comment by Konrud** [comment]
O.K. now when I checked it, thoroughly, once again, I think I know what made me think that it doesn't work. When Accordion's section is expanded it has its expanded style (color, background, etc...):
```
.accordion__trigger[aria-expanded="true"] {
    background: #1b75bc;
    color: #fff;
}
```
 so when you try to use `Home` and `Shift + Tab` keys it doesn't change its style into focused one but remains with the expanded style. But if you close it, it gets its focused style again.

**Comment by scottaohara** [comment]
Ok cool :)

I actually made #13 specifically about expanded button focus styles needing to be updated this morning.
