### ISSUE TITLE
Open an accordion panel using button

### ISSUE THREAD

**Issue by wshin93** [scottaohara/accessible_accordions#2]
Hello, I have been using your accordion and it's great.
But I have a question.

Inside each panel I have a button that says 'next step'. If it clicked it will open the next panel.

I used jquery to simulate a click on the accordion header (trigger?) when 'next step' is clicked.

It does open the next panel, however the opened panel class is 'was-active', and the previous panel class is still 'is-active'

How can I fix this? sorry if my explanation is confusing. Hope you can help. Thanks!

**Comment by scottaohara** [comment]
do you have a live example somewhere?

**Comment by scottaohara** [comment]
Also, going to close this issue since it's not an actual issue with the plugin, but the extension you're trying to add to it.  

Again, if you have a code example you can share, i'd be happy to take a look at it.  You can continue to post in this thread.
