### ISSUE TITLE
Possible `id` collision

### ISSUE THREAD

**Issue by kevincennis** [scottaohara/accessible_accordions#5]
As written, with multiple accordions, there's a possibility that the same randomly-generated `id` could be applied to multiple elements.

Might be safer to do something like this toward the top of your closure:

```js
var idCounter = 0;
```

Then, at the top of `Accordion.create()` (before the loop starts)

```js
idCounter += 1;
```

And to generate the actual `id` per element:

```js
self.id = 'acc_' + idCounter + '-' + i;
```

This way, since you're auto-incrementing, it impossible to ever have any collisions (until you get to `9007199254740991`, which is the maximum safe integer in JS and – you know – probably not gonna be a problem).

**Comment by scottaohara** [comment]
new code pushed.  Thank you again @kevincennis
