### ISSUE TITLE
question about 2 lines of text in header area

### ISSUE THREAD

**Issue by MadCowWeb** [scottaohara/accessible_accordions#8]
not sure if this is the place for questions, but I'm trying to get 2 different lines of text in my "header" an h2 and a p.
```
<li class="accordion-item">
  <img src="<?php the_sub_field('image'); ?>" />
  <h2 class="accordion-heading" data-aria-accordion-heading><?php the_sub_field('title'); ?></h2>
*(Ideally another line of text here)*
  <div class="accordion-panel" data-aria-accordion-panel>
   	<p><?php the_sub_field('main_content'); ?></p>
  </div>
</li>
```

I've tried inserting it inside the h2, putting it below the h2, adding a div to hold the h2 and the p. those all seem to break the button.
any direction would be awesome!

(you can see it here if you'd like:   https://globaltoolkit.wpengine.com/test-page/)   down at the bottom.

_Originally posted by @RidgeviewTech in https://github.com/scottaohara/a11y_accordions/issues/7#issuecomment-458757991_

**Comment by scottaohara** [comment]
Hi @RidgeviewTech, 
The script doesn't currently support that sort of markup.

from the readme:
>a <button> is dynamically created and inserted into the data-aria-accordion-heading element. The previous text of the heading is then inserted into this button. Presently, this strips out any previous HTML tags that were in the heading and only retains the text string.

I am going to keep this issue open as I'm going to consider if there's something that could be done here in some updates I have planned.  But generally I'm a little unsure how i feel about multiple strings of text serving as a button's accessible name.

**Comment by MadCowWeb** [comment]
Thanks for the reply! and thanks for the great chunk of code. It works great!

**Comment by darrickfabian** [comment]
@scottaohara any workaround for this? Need 'sup' tags:/

**Comment by scottaohara** [comment]
happy to review a PR :) 

i've unfortunately had little time to spend on some of these projects, and likely won't have time again until the new year.
